keys:
  - &user_adtya age1w5rvr4nl8xvjjxpct4e2a2eajvm79v4r9nyxrcn40fm8d7h9l9cqkk0jtt
  - &user_adtya_gloria age1r4hmqwyy4mvs0gjvcx5l06qvxfjt56ec2y00qmdgmyrrl2y0ysmspqc6cd
  - &host_skipper age1mhks8qmhjrtc2u5ufvp3pv2hn7tkadvmscnp7wd0ywmnse0szctqsnpy0a
  - &host_thor age17r9l5yuhw0ydal82ydgeq5xa9vh4l0xln3gp49r64xg84sphlcps0e5euq
  - &host_gwen age17zlfcp0lqw2xdr6ruj85nl2zd7dtc74t8qtxctyuncuqlvzmm4cs3hzujr
  - &host_rico0 age106k9u5ns9h7smh3gqc40k9fft5emknvq669qdv8a29ak3ah4j38s5ng2gt
  - &host_rico1 age1829x4l8vdhcn97af0zq898tupll0smrqywxka4pswkt6mtn8qp7qqnnnl4
  - &host_rico2 age19uy6xerll6st3s3ftfpy7075m9eetm2288l2w07k7ek6z2l3ef6qfw34cf
  - &host_wynne age1jyaf9rn5d5pqjh60shs2q5hs98fwugak8z6cs6qs7yuc3wntugmsumxmv0
  - &host_layne age1k2wpm88wms6hx3ldvu0n2je7pag9fexs9eq0e8hlkfcs2dx9eg9qlkf95d
  - &host_bifrost age19utpmjh07n2s860s9h2mqmwfh836ne0r2nkdl6444nvsyfrudcss9nvzck
creation_rules:
  - path_regex: secrets.yaml
    key_groups:
      - age:
          - *user_adtya 
          - *user_adtya_gloria 
          - *host_skipper 
          - *host_thor
          - *host_gwen 
          - *host_rico0 
          - *host_rico1 
          - *host_rico2 
          - *host_wynne 
          - *host_layne 
          - *host_bifrost 
