keys:
  - &skipper_host_ed25519 age1mhks8qmhjrtc2u5ufvp3pv2hn7tkadvmscnp7wd0ywmnse0szctqsnpy0a
  - &rico1_host_ed25519 age1q6g2czy468c3fcdwvafru6rzhmr2edd8mzhjfs6mevhmt7z2zdsswnwe77
creation_rules:
  - path_regex: secrets.yaml
    key_groups:
    - age:
      - *skipper_host_ed25519
      - *rico1_host_ed25519
