name: Update inputs

on:
  schedule:
    - cron: "0 0 * * 5"
  workflow_dispatch:

jobs:
  update-inputs:
    runs-on: ubuntu
    container:
      image: node:20-bookworm
    name: Update Inputs
    steps:
      - uses: https://github.com/actions/checkout@v3
        with:
          token: ${{ github.token }}
          ref: ${{ github.head_ref }}
      - uses: https://github.com/cachix/install-nix-action@v20
        with:
          github_access_token: ${{ github.token }}
      - name: Update inputs
        run: |
          nix flake update
      - name: Commit changes
        uses: https://github.com/EndBug/add-and-commit@v9
        with:
          message: 'Actions: Update Inputs'
          default_author: github_actions
          add: 'flake.lock'
