name: Tailscale ACLs
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - tailnet/**
  pull_request:
    branches: ["main"]
    paths:
      - tailnet/**
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test ACL
        id: test-acl
        uses: tailscale/gitops-acl-action@v1
        with:
          policy-file: tailnet/policy.hujson
          oauth-client-id: ${{ secrets.TS_OAUTH_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET}}
          tailnet: ${{ secrets.TS_TAILNET }}
          action: test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy ACL
        if: github.event_name == 'push'
        id: deploy-acl
        uses: tailscale/gitops-acl-action@v1
        with:
          policy-file: tailnet/policy.hujson
          oauth-client-id: ${{ secrets.TS_OAUTH_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET}}
          tailnet: ${{ secrets.TS_TAILNET }}
          action: apply
