name: Update inputs

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-inputs:
    runs-on: ubuntu-latest
    name: Update Inputs
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
          ref: ${{ github.head_ref }}
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ github.token }}
      - name: Update inputs
        run: |
          nix flake update
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: GitHub Actions
          commit_user_email: ""
          commit_author: ""
          commit_message: 'Update Inputs'
          file_pattern: flake.lock
          push_options: '--force'
